version: '3.8'

services:
  # 1. PostgreSQL (Veritabanı)
  postgres:
    image: postgres:15-alpine
    container_name: kalorilens_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: kalorilens_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. pgAdmin (Postgres Yönetim Paneli)
  pgadmin:
    image: dpage/pgadmin4
    container_name: kalorilens_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kalorilens.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # 3. MongoDB (Veritabanı)
  mongo:
    image: mongo:6.0
    container_name: kalorilens_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 4. Mongo Express (Mongo Yönetim Paneli)
  mongo-express:
    image: mongo-express
    container_name: kalorilens_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  postgres_data:
  mongo_data:
