version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: kalorilens
      POSTGRES_PASSWORD: kalorilens
      POSTGRES_DB: kalorilens
    ports: [ "5432:5432" ]
  mongodb:
    image: mongo:7
    ports: [ "27017:27017" ]
